[package]
name = "nvmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
dirs = "5.0.1"
fs_extra = "1.3.0"
lazy_static = "1.4.0"
regex = "1.9.5"
serde_json = "1.0.105"
