[package]
name = "nvmd"
version = "2.4.0"
edition = "2021"
authors = ["The1111mp@outlook.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
chrono = "0.4.31"
clap = { version = "4.4.4", features = ["derive"] }
dirs = "5.0.1"
fs_extra = "1.3.0"
lazy_static = "1.4.0"
regex = "1.9.5"
serde_json = "1.0.105"
version-compare = "0.1.1"
